-- Load synthetic case study data
USE SCHEMA CUSTOMER_SUCCESS_DATA.ANALYTICS;

INSERT INTO case_studies (title, company_name, industry_vertical, content, key_results, use_cases, channels_used, publication_date, read_time_minutes, metadata)
VALUES
('Streaming Platform Increases User Engagement by 45% with Cross-Channel Campaigns',
 'StreamNow Media',
 'Media & Entertainment',
 'StreamNow Media, a leading subscription streaming service, faced challenges with declining user engagement and rising churn rates. By implementing a comprehensive cross-channel messaging strategy, they created personalized customer journeys that adapted to user behavior in real-time. The platform leveraged predictive analytics to identify at-risk subscribers and deployed targeted re-engagement campaigns across email, push notifications, and in-app messages.',
 'Achieved 45% increase in daily active users, reduced churn by 28%, improved content discovery leading to 60% more titles viewed per subscriber, and increased premium subscription conversions by 35%',
 'Retention,Reduce Churn,Engagement',
 'Email,Push,In-App Messages,Content Cards',
 '2025-08-19',
 5,
 TO_VARIANT(PARSE_JSON('{"tags": ["cross-channel", "personalization", "predictive-analytics"], "featured": true}'))),

('Sports Betting App Drives 60% Conversion Rate with Real-Time Personalization',
 'BetWise Gaming',
 'Media & Entertainment',
 'BetWise Gaming needed to stand out in a competitive sports betting market. They implemented AI-powered personalization that analyzed user preferences, betting patterns, and real-time sports events to deliver hyper-relevant messaging. The platform used behavioral triggers to send timely notifications about odds changes, game updates, and personalized betting suggestions.',
 '60% conversion rate on targeted campaigns, 3x increase in daily bet volume, 85% message open rate for time-sensitive notifications, and 40% growth in customer lifetime value',
 'Acquisition,Engagement,Conversions',
 'SMS,Push,In-App Messages,Email',
 '2025-06-19',
 4,
 TO_VARIANT(PARSE_JSON('{"tags": ["AI", "real-time", "conversions"], "featured": false}'))),

('Music Streaming Service Boosts Premium Subscriptions with AI-Driven Campaigns',
 'SoundWave Music',
 'Media & Entertainment',
 'SoundWave Music wanted to convert free-tier users to premium subscribers while maintaining high engagement. They deployed machine learning models to predict conversion likelihood and used Canvas Flow to orchestrate multi-step journeys. Content Cards highlighted premium features contextually based on user listening habits.',
 'Premium subscription conversions increased by 52%, free user retention improved by 38%, engagement with Content Cards reached 72%, and customer satisfaction scores rose by 25 points',
 'Onboarding,Retention,Conversions',
 'Email,Content Cards,In-App Messages,Push',
 '2025-04-19',
 6,
 TO_VARIANT(PARSE_JSON('{"tags": ["AI", "canvas-flow", "content-cards"], "featured": true}'))),

('Gaming Publisher Reduces Churn by 20% with Predictive User Modeling',
 'PixelForge Studios',
 'Media & Entertainment',
 'PixelForge Studios needed to reduce player churn in their mobile gaming portfolio. By implementing predictive user modeling with streaming data integration, they identified early warning signs of disengagement. The team created automated workflows that triggered personalized interventions based on player behavior patterns.',
 'Achieved 20% reduction in 30-day churn, increased daily active users by 33%, improved in-app purchase conversion by 41%, and boosted player satisfaction scores',
 'Reduce Churn,Engagement,Retention',
 'Push,In-App Messages,Email',
 '2025-09-19',
 3,
 TO_VARIANT(PARSE_JSON('{"tags": ["predictive-analytics", "dynamic-segmentation", "gaming"], "featured": false}'))),

('Podcast Platform Increases Listener Engagement with Cross-Channel Messaging',
 'AudioHub Network',
 'Media & Entertainment',
 'AudioHub Network sought to increase listener engagement and drive subscriptions to their premium ad-free tier. They implemented a cross-channel strategy that combined email newsletters with push notifications for new episode releases. The platform used Liquid personalization to create dynamic content based on listening history.',
 'Listening sessions increased by 55%, premium subscription conversions up 47%, email engagement rates improved to 42%, and average listening time per user grew by 31%',
 'Engagement,Retention,Conversions',
 'Email,Push,Content Cards,In-App Messages',
 '2025-07-19',
 5,
 TO_VARIANT(PARSE_JSON('{"tags": ["cross-channel", "personalization", "audio"], "featured": true}'))),

('Digital News Publisher Drives Subscriptions with Interactive Campaigns',
 'NewsHub Digital',
 'Media & Entertainment',
 'NewsHub Digital needed to convert casual readers into paying subscribers. They created interactive cross-channel campaigns featuring in-app message surveys to understand reader preferences. Based on survey responses, they delivered personalized content recommendations and subscription offers.',
 'Subscription conversions increased by 64%, reader engagement grew by 48%, survey completion rate of 58%, and customer retention improved by 35%',
 'Acquisition,Engagement,Conversions',
 'Email,In-App Messages,Push,Survey',
 '2025-05-19',
 4,
 TO_VARIANT(PARSE_JSON('{"tags": ["survey", "interactive", "subscriptions"], "featured": false}'))),

('Video Platform Enhances User Experience with Content Discovery',
 'WatchNext Video',
 'Media & Entertainment',
 'WatchNext Video struggled with content discovery as their library grew. They implemented an intelligent messaging strategy that used viewing patterns and preferences to suggest relevant content. Content Cards within the app showcased personalized recommendations updated in real-time.',
 'Content discovery improved by 71%, watch time per user increased by 44%, user satisfaction scores up 29 points, and app engagement frequency grew by 56%',
 'Engagement,Retention,Personalization',
 'Content Cards,Push,In-App Messages,Email',
 '2025-03-19',
 5,
 TO_VARIANT(PARSE_JSON('{"tags": ["content-discovery", "personalization", "video"], "featured": true}')));
